name: Check TLA

on:
  # Triggers the workflow on push or pull request on master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-market3:
    name: Check Market3.tla
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: fetch TLC
        run: |
          wget https://github.com/tlaplus/tlaplus/releases/download/v1.8.0/tla2tools.jar
      - name: Check Market3 (TLC)
        run: |
          java -jar tla2tools.jar Machine_Checked/MCMarket3.tla -config ./Machine_Checked/MCMarket3.cfg -simulate num=1000
  check-market:
    name: Check Market.tla
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: fetch TLC
        run: |
          wget https://github.com/tlaplus/tlaplus/releases/download/v1.8.0/tla2tools.jar
      - name: Check Market (TLC)
        run: |
          java -jar tla2tools.jar Market/MCMarket.tla -config ./Market/MCMarket.cfg -simulate num=1000
